name: 'Generate docker tag'
description: 'Generate valid docker tag from source ref or user input'
inputs:
  input:
    description: 'The branch, tag, SHA or custom name to build a tag for'
    required: true
outputs:
  docker_tag:
    description: "The docker tag to use"
    value: ${{ steps.docker_tag.outputs.docker_tag }}
runs:
  using: "composite"
  steps:
    - name: Generate valid docker tag
      id: docker_tag
      shell: bash
      run: |
        docker_tag="${{ inputs.input }}"
        if [ -z "$docker_tag" ]; then
          echo "Cannot generate tag for empty input"
          exit 1
        fi

        # replace all special characters to - (allowed: -_.)
        # fix/bug#123 -> fix-bug-123  
        # pr@123      -> pr-123
        # test-1.2    -> test-1.2
        docker_tag="$(echo "$docker_tag" | sed 's/[^a-zA-Z0-9._]/-/g')"

        # trim leading dashes
        # -fix        -> fix
        docker_tag="$(echo "$docker_tag" | sed 's/^-*//')"


        echo "docker_tag=$docker_tag" >> $GITHUB_OUTPUT
        echo "Docker Tag: $docker_tag"
