name: Manifest
description: Build and push a docker manifest to Docker Hub

inputs:
  platforms:
    description: Comma-separated list of platforms (e.g. linux/amd64,linux/arm64)
    type: string
    required: true
  source_repository:
    description: The source repository to build from
    type: string
    required: true
  source_ref:
    description: The branch, tag or SHA to checkout and build from
    type: string
    required: true
  target_tag:
    description: Docker hub tag to push to
    type: string
    required: true
  target_repository:
    description: Docker hub repository to push to
    type: string
    required: true
  # Secrets
  DOCKER_USERNAME:
    required: true
  DOCKER_PASSWORD:
    required: true
  MACOS_PASSWORD:
    required: true

runs:
  using: composite
  steps:
  - name: Checkout this repo
    uses: actions/checkout@v3
  - name: Check out source repository
    uses: actions/checkout@v3
    with:
      repository: ${{ inputs.source_repository }}
      path: source
      ref: ${{ inputs.source_ref }}
  - name: get git commit hash
    id: git_commit_hash
    shell: bash
    run: |
      cd source
      echo "git_commit_hash=$(echo $(git log --pretty=format:'%h' -n 1))" >> $GITHUB_OUTPUT
  - name: Generate images list
    id: generate_images_list
    shell: bash
    run: |
      PLATFORMS="${{ inputs.platforms }}"
      IMAGES=""

      IFS=',' read -ra ADDR <<< "$PLATFORMS"
      for platform in "${ADDR[@]}"; do
          slug=$(echo "$platform" | tr '/' '-')
          IMAGES+="${{ inputs.target_repository }}:${{ inputs.target_tag }}-$slug "
      done

      IMAGES=${IMAGES::-1}  # Remove the trailing space
      echo "images=$IMAGES" >> $GITHUB_OUTPUT
  - name: Set up Docker Context for Buildx
    shell: bash
    id: buildx-context
    run: |
      docker context use builders || docker context create builders
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2
    with:
      endpoint: builders
  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ inputs.DOCKER_USERNAME }}
      password: ${{ inputs.DOCKER_PASSWORD }}
  - name: Create and push manifest images
    shell: bash
    run: |
      docker buildx imagetools create --dry-run -t ${{ inputs.target_repository }}:${{ inputs.target_tag }} -t ${{ inputs.target_repository }}:${{ inputs.target_tag }}-${{ steps.git_commit_hash.outputs.git_commit_hash }} ${{ steps.generate_images_list.outputs.images }}
      docker buildx imagetools create -t ${{ inputs.target_repository }}:${{ inputs.target_tag }} -t ${{ inputs.target_repository }}:${{ inputs.target_tag }}-${{ steps.git_commit_hash.outputs.git_commit_hash }} ${{ steps.generate_images_list.outputs.images }}
