name: Manifest
description: Build and push a docker manifest to another registry

inputs:
  target_registry:
    description: Target registry to push the images to
    type: string
    required: true
  source_images:
    description: List of image tags to push to the other registry
    type: string
    required: true
  DOCKER_USERNAME:
    required: true
  DOCKER_PASSWORD:
    required: true

runs:
  using: composite
  steps:
  - name: Check if there is atleast one image
    if: ${{ inputs.source_images == '[]' || inputs.source_images == '' }}
    shell: bash
    run: exit 1
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3
  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      registry: ${{ inputs.target_registry }}
      username: ${{ inputs.DOCKER_USERNAME }}
      password: ${{ inputs.DOCKER_PASSWORD }}
  
  - name: Create and push manifest images for other registry
    shell: bash
    run: |
      images="${{ inputs.source_images }}"
      for image in $images; do
        target_tag=$(echo "${{ inputs.target_registry }}$image" | sed -E 's/^\s*.*:\/\///g')
        echo "copy $image to $target_tag"
        docker buildx imagetools create --dry-run -t $target_tag $image
        docker buildx imagetools create -t $target_tag $image
      done

