name: 'Setup'
description: 'Read and parse config files for specified client'
inputs:
  client:
    description: 'The client'
    required: true
outputs:
  platforms:
    description: "Matrix of platforms and runner to use"
    value: ${{ steps.setup_platforms.outputs.platforms }}
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: mikefarah/yq@6609ed76ecb69f9d8254345292d90ea72f641715 # v4.35.1
    - name: Generate platform and runner matrix from config files
      id: setup_platforms
      shell: bash
      run: |
        PLATFORMS_JSON="["
        client="${{ inputs.client }}"

        # Extract the platforms for the specified client
        platforms=$(yq e ".$client[]" platforms.yaml)

        for platform in $platforms; do
          slug=$(echo "$platform" | tr '/' '-')
          runner=$(yq e ".\"$platform\"" runners.yaml)
          PLATFORMS_JSON+="{\"platform\":\"$platform\", \"runner\":\"$runner\", \"slug\":\"$slug\"},"
        done

        PLATFORMS_JSON="${PLATFORMS_JSON%,}]"
        echo "platforms=$PLATFORMS_JSON" >> $GITHUB_OUTPUT
