name: Build grandine docker image

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The source grandine repository to build from
        default: grandinetech/grandine
        type: string
        required: true
      ref:
        description: The branch, tag or SHA to checkout and build from
        default: develop
        type: string
        required: true
      docker_tag:
        description: Override target docker tag (defaults to the above source ref if left blank)
        type: string
        required: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.setup.outputs.platforms }}
      target_tag: ${{ steps.tag.outputs.docker_tag }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Prepare Matrix
        id: setup
        uses: ./.github/actions/prepare
        with:
          client: 'grandine'
      - name: Generate target tag
        id: tag
        uses: ./.github/actions/docker-tag
        with:
          input: ${{ inputs.docker_tag || inputs.ref }}
  deploy:
    needs:
      - prepare
    runs-on: ${{ matrix.runner }}
    continue-on-error: true
    strategy:
      matrix:
        include: ${{fromJson(needs.prepare.outputs.platforms)}}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/install-deps
        with:
          repository: ${{ inputs.repository }}
      - uses: ./.github/actions/deploy
        with:
          source_repository: ${{ inputs.repository }}
          source_ref: ${{ inputs.ref }}
          build_script: ./grandine/build.sh
          target_dockerfile: ./grandine/Dockerfile
          target_tag: ${{ needs.prepare.outputs.target_tag }}-${{ matrix.slug }}
          target_repository: ethpandaops/grandine
          platform: ${{ matrix.platform }}

          DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
          MACOS_PASSWORD: "${{ secrets.MACOS_PASSWORD }}"
          GOPROXY: "${{ vars.GOPROXY }}"
  deploy-minimal:
    needs:
      - prepare
    runs-on: ${{ matrix.runner }}
    continue-on-error: true
    strategy:
      matrix:
        include: ${{fromJson(needs.prepare.outputs.platforms)}}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/install-deps
        with:
          repository: ${{ inputs.repository }}
      - uses: ./.github/actions/deploy
        with:
          source_repository: ${{ inputs.repository }}
          source_ref: ${{ inputs.ref }}
          build_script: ./grandine/build.sh
          target_dockerfile: ./grandine/Dockerfile.minimal
          target_tag: ${{ needs.prepare.outputs.target_tag }}-minimal-${{ matrix.slug }}
          target_repository: ethpandaops/grandine
          platform: ${{ matrix.platform }}
          harbor_registry: ${{ vars.HARBOR_REGISTRY }}
          HARBOR_USERNAME: "${{ vars.HARBOR_USERNAME }}"
          HARBOR_PASSWORD: "${{ secrets.HARBOR_PASSWORD }}"

          DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
          MACOS_PASSWORD: "${{ secrets.MACOS_PASSWORD }}"
          GOPROXY: "${{ vars.GOPROXY }}"
  manifest:
    needs:
      - prepare
      - deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/manifest
        with:
          source_repository: ${{ inputs.repository }}
          source_ref: ${{ inputs.ref }}
          target_tag: ${{ needs.prepare.outputs.target_tag }}
          target_repository: ethpandaops/grandine
          platforms: ${{ needs.prepare.outputs.platforms }}

          DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
  manifest-minimal:
    needs:
      - prepare
      - deploy-minimal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/manifest
        with:
          source_repository: ${{ inputs.repository }}
          source_ref: ${{ inputs.ref }}
          target_tag: ${{ needs.prepare.outputs.target_tag }}-minimal
          target_repository: ethpandaops/grandine
          platforms: ${{ needs.prepare.outputs.platforms }}

          DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - prepare
      - deploy
      - deploy-minimal
      - manifest
      - manifest-minimal
    if: failure()
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@2f38abc8877c7e8d2b0ded0cfd9599632014279f # v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
