name: Build besu docker image

on:
  workflow_dispatch:
    inputs:
      repository: 
        description: The source besu repository to build from
        default: hyperledger/besu
        type: string
        required: true
      ref:
        description: The branch, tag or SHA to checkout and build from
        default: main
        type: string
        required: true
      docker_tag:
        description: Override target docker tag (defaults to the above source ref if left blank)
        type: string
        required: false
      runs_on:
        description: The runner to use
        type: choice
        required: true
        default: ubuntu-latest
        options:
        - ubuntu-latest
        - services-medium-cpu


jobs:
  besu:
    runs-on: ${{ inputs.runs_on }}
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
        with:
          repository: ${{ inputs.repository }}
      - uses: ./.github/actions/deploy
        with:
          source_repository: ${{ inputs.repository }}
          source_ref: ${{ inputs.ref }}
          build_script: ./besu/build.sh
          target_tag: ${{ inputs.docker_tag || inputs.ref }}
          target_repository: ethpandaops/besu
          platform: ${{ matrix.platform }}
          DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
