name: Build ethrex docker image

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The source ethrex repository to build from
        default: lambdaclass/ethrex
        type: string
        required: true
      ref:
        description: The branch, tag or SHA to checkout and build from
        default: main
        type: string
        required: true
      docker_tag:
        description: Override target docker tag (defaults to the above source ref if left blank)
        type: string
        required: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.setup.outputs.platforms }}
      target_tag: ${{ steps.tag.outputs.docker_tag }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Prepare Matrix
        id: setup
        uses: ./.github/actions/prepare
        with:
          client: 'ethrex'
      - name: Generate target tag
        id: tag
        uses: ./.github/actions/docker-tag
        with:
          input: ${{ inputs.docker_tag || inputs.ref }}
  deploy:
    needs:
      - prepare
    runs-on: ${{ matrix.runner }}
    continue-on-error: true
    strategy:
      matrix:
        include: ${{fromJson(needs.prepare.outputs.platforms)}}
    outputs:
      git_commit_hash: ${{ steps.deploy.outputs.git_commit_hash }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/install-deps
        with:
          repository: ${{ inputs.repository }}
      - uses: ./.github/actions/deploy
        id: deploy
        with:
          source_repository: ${{ inputs.repository }}
          source_ref: ${{ inputs.ref }}
          target_tag: ${{ needs.prepare.outputs.target_tag }}-${{ matrix.slug }}
          target_repository: ethpandaops/ethrex
          platform: ${{ matrix.platform }}

          DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
          MACOS_PASSWORD: "${{ secrets.MACOS_PASSWORD }}"
          GOPROXY: "${{ vars.GOPROXY }}"
  manifest:
    needs:
      - prepare
      - deploy
    runs-on: ubuntu-latest
    outputs:
      docker_images: ${{ steps.manifest.outputs.docker_images }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/manifest
        id: manifest
        with:
          source_repository: ${{ inputs.repository }}
          source_ref: ${{ inputs.ref }}
          target_tag: ${{ needs.prepare.outputs.target_tag }}
          target_repository: ethpandaops/ethrex
          platforms: ${{ needs.prepare.outputs.platforms }}
          harbor_registry: ${{ vars.HARBOR_REGISTRY }}
          HARBOR_USERNAME: "${{ vars.HARBOR_USERNAME }}"
          HARBOR_PASSWORD: "${{ secrets.HARBOR_PASSWORD }}"
          git_commit_hash: ${{ needs.deploy.outputs.git_commit_hash }}

          DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - prepare
      - deploy
      - manifest
    if: failure()
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@1766a33bf571acdcc0678f00da4fb83aad01ebc7 # v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}