name: Build reth docker image

on:
  workflow_dispatch:
    inputs:
      repository: 
        description: The source reth repository to build from
        default: paradigmxyz/reth
        type: string
        required: true
      ref:
        description: The branch, tag or SHA to checkout and build from
        default: main
        type: string
        required: true
      docker_tag:
        description: Override target docker tag (defaults to the above source ref if left blank)
        type: string
        required: false
      runs_on:
        description: The runner to use
        type: choice
        required: true
        default: ubuntu-latest
        options:
        - ubuntu-latest
        - services-medium-cpu

jobs:
  reth:
    runs-on: ${{ inputs.runs_on }}
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
        with:
          repository: ${{ inputs.repository }}
      - uses: ./.github/actions/deploy
        with:
          source_repository: ${{ inputs.repository }}
          source_ref: ${{ inputs.ref }}
          target_tag: ${{ inputs.docker_tag || inputs.ref }}
          target_repository: ethpandaops/reth
          platform: ${{ matrix.platform }}
          DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - reth
    if: failure()
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

