FROM ubuntu:latest

ARG ENTRY=/app/cmd/beacon-chain/beacon-chain
ENV ENTRY=${ENTRY}
WORKDIR /app/cmd/beacon-chain/beacon-chain.runfiles/prysm
ADD ./_beacon-chain /app/cmd/beacon-chain/beacon-chain
ADD ./entrypoint.sh /entrypoint.sh
RUN apt-get update && apt-get install -y ca-certificates libc6 && update-ca-certificates
RUN chmod +x /entrypoint.sh /app/cmd/beacon-chain/beacon-chain

ENTRYPOINT ["/entrypoint.sh"]
